### PR TITLE
convert material ui version 4 to 5

### PR DESCRIPTION
**Pull request by MounikaReddy15**
## Purpose
_Converting material ui version from 4 to 5_

## Further info
_Removed material ui libraries and added mui libraries_

## Ticket number
 #31

### CODE REVIEW

**Comment by yasmin2496** [comment]
Screenshot 2021-12-22 at 20 25 29
@MounikaReddy15 Can you check for this. In the modal the heading is not visible for "Add Issue"

**Comment by RadhikaPPatel** [comment]
@MounikaReddy15 Please resolve the conflict as well as link the issue to the PR.

**Review by RadhikaPPatel — CHANGES_REQUESTED** [review]
Error and warning logs coming in for Kanban View and New Project modal. Please check and fix this.

**Comment by MounikaReddy15** [comment]
Raised another pr which has material ui changes and warning changes

**Comment by MounikaReddy15** [comment]
Raised another pr which has material ui and warning changes

**Pull request closed without merging**
